version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - API_URL=http://server:3000
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=3000

networks:
  app-network: # Общая сеть для сервисов
